language: node_js
node_js:
  - 9

sudo: enabled
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/

cache:
  yarn: true
  directories:
    - node_modules

before_install: yarn global add greenkeeper-lockfile@1

install:
  - yarn install

before_script: greenkeeper-lockfile-update

script:
  - yarn run test
  - yarn run build

after_script: greenkeeper-lockfile-upload

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  name: "Zowie van Geest"
  email: zowie@zowievangeest.nl
  on:
    branch: master